### ISSUE TITLE
I have (github) Commitment Issues

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-1#1]
I keep trying to commit to GitHub, but keep getting rejected 👎   

"error: failed to push some refs to 'https://github.com/JacyAnderson/parachute-game.git'
Updates were rejected because the remote contains work that you do not have locally."

I'm in the lobby if someone can give me any pointers on how stay loyal to my repository.

**Comment by ZebGirouard** [comment]
Jacy is all set.
