### ISSUE TITLE
Object collision for generated rockets

### ISSUE THREAD

**Issue by JacyAnderson** [den-materials/project-1#2]
In need of guidance on applying object collision to generated rockets (potentially infinite) when then meet a player.

Here's some links I used for applying collision to my players, but they don't help solve my rocket issue:

http://stackoverflow.com/questions/4230029/jquery-javascript-collision-detection
http://stackoverflow.com/questions/5930020/detecting-div-collision

My squad had no idea how to help. :(

**Comment by ZebGirouard** [comment]
Nick resolved
