### ISSUE TITLE
Console Error Message

### ISSUE THREAD

**Issue by CRCastells** [den-materials/project-1#23]
I have encountered a very strange error that I simply do not know how to handle. 
The error is: 
`Access to Image at 'http://img13.deviantart.net/7fc3/i/2012/288/4/7/volt_sprite_sheet_by_kwelfury-d5hx008.png' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
p5.min.js:31 > p5.js says: It looks like there was a problem loading your image. Try checking if the file path [http://img13.deviantart.net/7fc3/i/2012/288/4/7/volt_sprite_sheet_by_kwelfury-d5hx008.png] is correct, hosting the image online, or running a local server.`
The only useful resource I found on the subject was https://stackoverflow.com/questions/41965066/access-to-image-from-origin-null-has-been-blocked-by-cors-policy

However, as the response details, I have swapped out my file for an online hosted image.
Yet, the error still remains even after using this hosted file.
For reference, the file I am using is a sprite-sheet in my JS file to load animation on top of my sprites. `function preload() {
 var sprite_sheet = loadSpriteSheet('http://img13.deviantart.net/7fc3/i/2012/288/4/7/volt_sprite_sheet_by_kwelfury-d5hx008.png', 171, 158, 10);
  var animation = loadAnimation(sprite_sheet);
}`
I am using the P5.play.js library, which is built on-top of canvas.

**Comment by ZebGirouard** [comment]
Got 'em!
