### ISSUE TITLE
innerHTML

### ISSUE THREAD

**Issue by ntutchton** [den-materials/project-1#3]
I have a function that updates the 'innerHTML' of a document element, and I've confirmed that it is working... but the actual text of the element i'm updating doesn't change. 

some snippets:
//in Player()...
	this.timer = document.getElementsByClassName('timeCounter');
//...
//and the problem later on...
	if (player.active === true){
		setInterval(function(){
			player.time += 0.10;
			player.timer.innerHTML = (player.time.toPrecision(4));
			//console.log(player.timer.innerHTML);
                         //^^^^^^this works, but text doesn't change on screen
		}, 100);
	}
};

**Comment by ZebGirouard** [comment]
The ol' getElementsByClassName returns array, getElementById always returns single object issue.  Awesome troubleshooting and solid game, @ntutchton !
