### ISSUE TITLE
Hiding a particular div with click function

### ISSUE THREAD

**Issue by CamB17** [den-materials/project-1#6]
Asked Taylor also checked these...
http://stackoverflow.com/questions/30154868/how-to-make-visible-and-hide-particular-divs
http://stackoverflow.com/questions/5454023/js-jquery-hide-div-show-div-on-click

**Comment by ZebGirouard** [comment]
Cam off to a good start, will check in later

**Comment by ZebGirouard** [comment]
Woo hoo bug squashing!
